# Built with Jekyll 3.2.0

# Setup
title:               metalib
tagline:             ''
description:         'metaprogramming experiments'
url:                 'http://sschauss.github.io/metalib'
baseurl:             '/metalib'

# About/contact
author:
  name:              Simon Schau√ü
  url:               https://github.com/sschauss
  email:             sschauss@uni-koblenz.de

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  technologies:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]
